### PR TITLE
Upgrade ember-cli to 2.5.1 and install linters

### LINKED ISSUE #24: Add ember-cli-eslint

### LINKED ISSUE #25: Add ember-cli-template-lint

### PR DESCRIPTION
**Pull request by binhums**
Upgrades ember-cli to 2.5.1 and installs linters

 - ESlint (fixes #24) and
 - ember-template-lint (fixes #25).

Turns out we didn't have any significant existing violations.

N.B. I have not tested this with a screen reader. Do we have any policies on manual QA for this project?

### CODE REVIEW

**Comment by binhums** [comment]
Appears to be running into 1.13 issues with ember-cli-template-lint.

**Comment by nathanhammond** [comment]
Hey @rwjblue! Can you you help us figure out what is happening here in 1.13?

Error: https://travis-ci.org/ember-a11y/ember-a11y/jobs/134235615#L407
Source: https://github.com/rwjblue/ember-cli-template-lint/blob/master/lib/plugins/remove-configuration-html-comments.js#L12

**Comment by rwjblue** [comment]
We cannot rely on the `.traverse` API for removing the HTML Comments (since it doesn't exist until some time after 1.13). I'm on it...

**Comment by rwjblue** [comment]
Released ember-cli-template-lint@0.4.9 which should fix the issue here with 1.13.

**Comment by binhums** [comment]
Thanks @rwjblue, @nathanhammond amazing response times. I think this should be ready to merge.

**Pull request merged**
