### PR TITLE
Update to ember-cli 2.13

### PR DESCRIPTION
**Pull request by Robdel12**
## What is this?

This updates the addon to ember-cli 2.13. 

I spent about an hour trying to get `ember-try` testing with `ember-1.13` but didn't make any progress. If anyone wants to give it a shot that'd be great! I'm not opposed to dropping 1.13 either. 

- [ ] Decide on fixing 1.13 testing or dropping it

### CODE REVIEW

**Comment by krivaten** [comment]
@Robdel12 sorry for my hold up on this. I've been moving the last week from Ohio to Colorado. If you want, I can look and see if I can get the Ember 1.13 tests up and running again (The app I am using this on is sadly still 1.13 (Hoping to move to 2.4 in the next couple months)).

For those other tests that are failing, is that a Travis configuration that needs to be updated?

**Comment by krivaten** [comment]
Forgive my ignorance, but is there a reason I can't checkout your `rd/revive` branch? Or am I just missing some noob detail when trying to pull it down?

**Comment by krivaten** [comment]
@Robdel12 I made a couple changes here:

1. Re-enabled Ember 1.13 testing
2. Removed Node 0.12 from `.travis.yml` since Yarn doesn't support it, according to previous build failures.
3. Removed the `default` EMBER_TRY_SCENARIO

I'm not too familiar with Ember Try, so if any of those changes are dangerous, just let me know and I can go back to the drawing board.

**Comment by Robdel12** [comment]
@krivaten Nope that all sounds great!! Thank you for all your work on this :D

**Comment by Robdel12** [comment]
One last thing. @krivaten can you use this branch in your app to verify it doesn't break anything for a before merge sanity check?

**Comment by krivaten** [comment]
@Robdel12 sure thing. Will give it a shot in a few.

**Comment by krivaten** [comment]
@Robdel12 getting a green build locally for my changes.

**Pull request merged**
